apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-database
spec:
  strategy:
    type: RollingUpdate
  replicas: 1
  selector:
    matchLabels:
      app: user-database
  template:
    metadata:
      labels:
        app: user-database
    spec:
      containers:
        - name: user-database
          image: jpsoutost/user-database:latest
          ports:
            - containerPort: 80
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: k8s
            - name: SERVER_PORT
              value: "80"
            - name: KAFKA_URL_ACTIVE
              value: kafka-service:9092
---
apiVersion: v1
kind: Service
metadata:
  name: user-database-service
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: user-database
