spring:
  application:
    name: user-service
  zipkin:
    baseUrl: ${ZIPKIN_URL_ACTIVE:localhost:9411}
  kafka:
    bootstrap-servers: ${KAFKA_URL_ACTIVE:localhost:9092}
    consumer:
      group-id: groupId
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            value:
              default:
                type: academy.mindswap.restfulwebservice.persistence.models.User
            trusted:
              packages: academy.mindswap
    producer:
      client-id: example
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      retries: 2
    listener:
      poll-timeout: 1800000
      concurrency: 1
      ack-mode: record
  data:
    mongodb:
      uri: mongodb://mindswap123:123mindswap@cluster0-shard-00-00.e01hz.mongodb.net:27017,cluster0-shard-00-01.e01hz.mongodb.net:27017,cluster0-shard-00-02.e01hz.mongodb.net:27017/users?ssl=true&replicaSet=atlas-13mede-shard-0&authSource=admin&retryWrites=true&w=majority
      database: users
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:prod}
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
server:
  port: 8081



